version: "2"
services:
  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    environment: 
        - MONGO_DATA_DIR=/data/db